spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/saye_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect

app:
  security:
    demo-login-enabled: true