spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/backend_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

app:
  security:
    demo-login-enabled: true
